FROM ubuntu:18.04
MAINTAINER Cedric Arisdakessian <carisdak@hawaii.edu>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y wget unzip curl

# Install libreadline6 for Mothur
RUN echo "deb http://archive.ubuntu.com/ubuntu/ xenial main" >> /etc/apt/sources.list \
	&& apt-get update \
	&& apt-get install -y libreadline6

# Install VSEARCH
RUN curl -L "https://github.com/torognes/vsearch/releases/download/v2.11.1/vsearch-2.11.1-linux-x86_64.tar.gz" | tar xz -C /usr/local/bin

# Download databases
# RUN mkdir databases
# RUN curl -L "https://mothur.org/w/images/3/32/Silva.nr_v132.tgz" | tar xz -C databases
# RUN wget "https://files.plutof.ut.ee/doi/A1/C9/A1C964DFB03C2A1B37FA16784BA739C88F0941AC68560CEA54DD707F1CF00AC4.zip" -O unite_db.zip \
# 	&& unzip unite_db.zip && rm unite_db.zip
# RUN sed -e 's/|SH.*//g' -e 's/;/,/g' -e 's/__/:/g' -e 's/|/;tax=d:Eukaryota,/g' UNITE_public_all_02.02.2019.fasta \
# 	| iconv -f utf8 -t ascii//TRANSLIT > databases/unite_all_eukaryotes.fasta

# Install mothur versions
RUN wget "https://github.com/mothur/mothur/releases/download/v1.43.0/Mothur.linux_64.zip"
RUN unzip Mothur.linux_64.zip \
	&& rm -rf __MACOSX Mothur.linux_64.zip\
	&& mv mothur /usr/local/bin

RUN wget "https://github.com/mothur/mothur/releases/download/v1.41.3/Mothur.linux_64.zip"
RUN unzip Mothur.linux_64.zip \
	&& rm -rf __MACOSX Mothur.linux_64.zip\
	&& mv mothur /usr/local/bin/mothur_1-41-3

# Setup PATH
ENV PATH /usr/local/bin/mothur:/usr/local/bin/vsearch-2.11.1-linux-x86_64/bin:$PATH

WORKDIR /workspace
COPY . /workspace

CMD /bin/bash
